//@version=6
indicator("Entry signals", overlay = true)

high_ma  = ta.ema(close, 20)
medium_ma = ta.ema(close, 100)
low_ma = ta.sma(close, 200)
vol_sma = ta.ema(volume, 20)
volume_ok = volume > vol_sma //* 0.8  // lowered threshold
lookback_period = input.int(10, "Lookback Period", minval=3, maxval=100)

// --- Plot EMAs ---
plot(high_ma,  color=color.blue,  linewidth=2, title="EMA 20")
plot(medium_ma, color=color.green, linewidth=2, title="EMA 100")
plot(low_ma, color=color.purple, linewidth=2, title="EMA 200 HTF")

// --- Buy block ---
x_over_high = ta.crossover(close, high_ma)
medium_ma_above_low_ma = ta.barssince(medium_ma <= low_ma) >= lookback_period or na(ta.barssince(medium_ma <= low_ma))
uptrend = medium_ma_above_low_ma and high_ma > medium_ma and medium_ma > low_ma and (medium_ma - medium_ma[1]) > 0
buy_condition = x_over_high and volume_ok and uptrend and close > open

// --- Plot buy signals ---
alertcondition(buy_condition, "BUY", "buy")
plotshape(buy_condition, title="Buy Signal", style=shape.triangleup, location=location.belowbar, color=color.green, size=size.normal)

// --- Sell block ---
x_under_high = ta.crossunder(close,high_ma)
medium_ma_below_low_ma = ta.barssince(medium_ma >= low_ma) >= lookback_period or na(ta.barssince(medium_ma >= low_ma))
downtrend = medium_ma_below_low_ma and high_ma < medium_ma and medium_ma < low_ma and (medium_ma - medium_ma[1]) < 0
sell_condition = x_under_high and volume_ok and downtrend and close < open

// --- Plot sell signals ---
alertcondition(sell_condition, "SELL", "sell")
plotshape(sell_condition, title="Sell Signal", style=shape.triangledown, location=location.abovebar, color=color.red, size=size.normal)
